"""Tests for sub-F BP2 encoding primitive Halt 2 surface."""

from __future__ import annotations

import math
from pathlib import Path

import pytest
import yaml
from shapely.geometry import LineString, MultiLineString, MultiPolygon, Polygon

CONFIG_ROOT = Path(__file__).resolve().parents[3] / "configs" / "sub_f"
ENCODING_PRIMITIVES_PATH = CONFIG_ROOT / "encoding_primitives.yaml"
SENTINEL_INVENTORY_PATH = CONFIG_ROOT / "sentinel_inventory.yaml"


@pytest.fixture(scope="module")
def encoding_primitives() -> dict:
    assert ENCODING_PRIMITIVES_PATH.exists(), (
        "configs/sub_f/encoding_primitives.yaml must be generated by "
        "scripts/sub_f/analyze_geometry_primitives.py"
    )
    return yaml.safe_load(ENCODING_PRIMITIVES_PATH.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def sentinel_inventory() -> dict:
    return yaml.safe_load(SENTINEL_INVENTORY_PATH.read_text(encoding="utf-8"))


def test_encoding_primitives_status_is_locked(encoding_primitives):
    assert encoding_primitives["_status"] == "LOCKED"


def test_joint_surface_contains_exact_candidate_grid(encoding_primitives):
    rows = encoding_primitives["joint_surface"]
    actual = {(row["direction_count"], row["magnitude_quantum_m"]) for row in rows}
    expected = {
        (direction_count, magnitude_quantum_m)
        for direction_count in (8, 16, 24)
        for magnitude_quantum_m in (0.25, 0.5, 1.0)
    }
    assert actual == expected
    assert len(rows) == 9


@pytest.mark.parametrize(
    "field",
    [
        "analytical_angle_half_bin_deg",
        "analytical_magnitude_half_quantum_m",
        "analytical_l_inf_bound_m",
        "roundtrip_l_inf_mean_m",
        "roundtrip_l_inf_p50_m",
        "roundtrip_l_inf_p95_m",
        "roundtrip_l_inf_p99_m",
        "roundtrip_l_inf_max_m",
        "roundtrip_sample_counts",
        "roundtrip_skip_counts",
    ],
)
def test_joint_surface_rows_include_analytical_and_linf_fields(encoding_primitives, field):
    for row in encoding_primitives["joint_surface"]:
        assert field in row


@pytest.mark.parametrize(
    "field",
    [
        "right_angle_post_roundtrip_mean_deg",
        "right_angle_post_roundtrip_p50_deg",
        "right_angle_post_roundtrip_p95_deg",
        "right_angle_post_roundtrip_p99_deg",
        "right_angle_post_roundtrip_max_deg",
        "right_angle_abs_change_mean_deg",
        "right_angle_abs_change_p50_deg",
        "right_angle_abs_change_p95_deg",
        "right_angle_abs_change_p99_deg",
        "right_angle_abs_change_max_deg",
        "right_angle_measured_corner_count",
        "right_angle_skip_count",
    ],
)
def test_joint_surface_rows_include_right_angle_fields(encoding_primitives, field):
    for row in encoding_primitives["joint_surface"]:
        assert field in row


def test_input_characterization_reports_all_tile_inventory(encoding_primitives):
    source_scope = encoding_primitives["source_scope"]
    characterization = encoding_primitives["input_geometry_characterization"]
    assert source_scope["tile_count"] > 1
    assert source_scope["feature_count"] > 0
    assert characterization["geometry_type_feature_counts"]
    assert (
        sum(characterization["geometry_type_feature_counts"].values())
        == (source_scope["feature_count"])
    )
    assert characterization["measured_geometry_sample_counts"]["polylines"] > 0
    assert characterization["measured_geometry_sample_counts"]["polygon_exterior_rings"] > 0


def test_right_angle_input_characterization_reports_fraction(encoding_primitives):
    right_angle = encoding_primitives["right_angle_input_characterization"]
    assert right_angle["total_building_polygon_corner_count"] > 0
    assert "fraction_within_5_deg_of_90" in right_angle
    assert 0.0 <= right_angle["fraction_within_5_deg_of_90"] <= 1.0
    assert right_angle["definition"] == "abs(angle_deg - 90) <= 5"


def test_collinearity_derivation_reports_distribution_and_method(
    encoding_primitives,
):
    collinearity = encoding_primitives["collinearity_candidate_distribution"]
    assert collinearity["total_polyline_interior_triples"] > 0
    assert "collinear_candidate_triples" in collinearity
    assert "weak_empirical_p95_basis" in collinearity
    assert collinearity["weak_empirical_p95_basis"] == (
        collinearity["collinear_candidate_triples"] < 500
    )
    assert (
        collinearity["distribution_perpendicular_m"]["count"]
        == (collinearity["collinear_candidate_triples"])
    )
    assert "proposed_threshold_method" in collinearity
    assert "proposed_threshold_m" in collinearity
    assert "fixed_multiple_thresholds_m" in collinearity
    assert {"1x_magnitude_quantum", "2x_magnitude_quantum"} <= set(
        collinearity["fixed_multiple_thresholds_m"]
    )


def test_anchor_comparison_includes_flat_and_hierarchical(encoding_primitives):
    comparison = encoding_primitives["anchor_scheme_comparison"]
    assert {row["scheme"] for row in comparison} == {"flat", "hierarchical"}
    for row in comparison:
        assert row["anchor_vocab_size"] > 0
        assert row["tokens_per_anchor"] > 0
        assert row["mean_sequence_length_per_cell"] > 0
        assert row["p95_sequence_length_per_cell"] > 0


def test_anchor_vocab_derivation_is_spec_locked(encoding_primitives):
    quantum = encoding_primitives["proposed_lock"]["magnitude_quantum_m"]
    comparison = {row["scheme"]: row for row in encoding_primitives["anchor_scheme_comparison"]}
    assert comparison["flat"]["anchor_vocab_size"] == 2 * math.ceil(250 / quantum)
    assert comparison["flat"]["vocab_derivation"] == ("2 * ceil(250 / magnitude_quantum_m)")
    assert comparison["hierarchical"]["anchor_vocab_size"] == 96
    assert comparison["hierarchical"]["vocab_derivation"] == ("(16 coarse + 32 fine) * 2 axes")


def test_proposed_lock_uses_approved_halt2_values(
    encoding_primitives,
):
    proposed = encoding_primitives["proposed_lock"]
    assert proposed["direction_count"] == 48
    assert proposed["magnitude_quantum_m"] == 0.5
    assert proposed["anchor_scheme"] == "hierarchical"
    assert proposed["chunk_threshold_m"] == 32
    assert proposed["round_trip_l_inf_threshold_m"] == 4.8
    assert proposed["round_trip_l_inf_threshold_status"] == ("LOCKED_HALT_2_APPROVED")
    assert proposed["round_trip_angle_threshold_deg"] == 7.5
    assert proposed["round_trip_angle_threshold_status"] == ("LOCKED_HALT_2_APPROVED")
    assert proposed["collinearity_admission_perpendicular_m"] == 0.928048


def test_bp2_placeholder_fit_references_reserved_block(encoding_primitives):
    fit = encoding_primitives["bp2_placeholder_fit"]
    assert fit["placeholder_start_id"] == 300
    assert fit["placeholder_end_id"] == 1499
    assert fit["placeholder_range"] == "300..1499"
    assert fit["fits_placeholder"] is True
    assert fit["components"]["anchor_vocab_size"] == 96
    assert (
        fit["components"]["direction_vocab_size"]
        == (encoding_primitives["proposed_lock"]["direction_count"])
    )
    assert fit["components"]["magnitude_vocab_size"] == 65


def test_encoding_primitives_lock_metadata_preserves_methodology(
    encoding_primitives,
):
    lock = encoding_primitives["lock_metadata"]
    assert lock["halt"] == "Halt 2"
    assert lock["status"] == "APPROVED_LOCKED"
    assert lock["measurement_methodology"]["deterministic_seed"] == 20260523
    assert lock["measurement_methodology"]["l_inf_scope"] == "polyline_only"
    assert lock["measurement_methodology"]["angle_threshold_scope"] == (
        "non_catastrophic_right_angle_corners_only"
    )
    assert lock["measurement_methodology"]["catastrophic_angle_exclusion"] == (
        "post_roundtrip_abs_deviation_from_90_deg > 45"
    )
    assert lock["cascade_8_candidate"]["candidate"] == ("BP2 anchor + direction-bin alignment")
    assert "cascade #8" in lock["cascade_8_candidate"]["note"]
    assert lock["chunking_classification"]["classification"] == ("chunking_is_no_op_on_test_sample")
    assert lock["chunking_classification"]["reference"] == ("Continuation #2 Item A")
    assert lock["source_config_cross_references"] == [
        "configs/sub_f/semantic_vocab.yaml",
        "configs/sub_f/unknown_family.yaml",
        "configs/sub_f/sentinel_inventory.yaml",
    ]


def test_sentinel_inventory_locks_bp2_subranges(sentinel_inventory):
    # Post commit 4c4f880 (2026-05-28 sentinel-inventory fix):
    # structural_sentinels at 509+510 consumed from reserved_v2_headroom front.
    bp2 = sentinel_inventory["bp2_encoding_primitives"]
    assert bp2["start_id"] == 300
    assert bp2["end_id"] == 1499
    assert bp2["status"] == (
        "LOCKED at Halt 2 approval; structural_sentinels consumed at T8 plan-write 2026-05-28"
    )
    assert bp2["placeholder"] is False
    assert bp2["used_count"] == 211
    assert bp2["reserved_count"] == 989
    assert bp2["sub_blocks"] == {
        "anchor": {"start_id": 300, "end_id": 395, "slot_count": 96},
        "direction": {"start_id": 396, "end_id": 443, "slot_count": 48},
        "magnitude": {"start_id": 444, "end_id": 508, "slot_count": 65},
        "reserved_v2_headroom": {
            "start_id": 511,
            "end_id": 1499,
            "slot_count": 989,
        },
    }
    assert "bp2_encoding_primitives_placeholder" not in sentinel_inventory


def test_sentinel_inventory_locks_bp7_block(sentinel_inventory):
    bp7 = sentinel_inventory["bp7_boundary_ref"]
    assert bp7["start_id"] == 1500
    assert bp7["end_id"] == 1599
    assert bp7["placeholder"] is False
    assert bp7["status"] == "LOCKED at Halt 7 approval"


def test_linf_decomposition_reports_top_50_and_driver_summary(
    encoding_primitives,
):
    decomposition = encoding_primitives["l_inf_decomposition_proposed_24_0_5"]
    assert decomposition["candidate"] == {
        "direction_count": 24,
        "magnitude_quantum_m": 0.5,
        "geometry_class": "polylines",
    }
    assert decomposition["sample_count"] == 1000
    assert len(decomposition["top_50_worst_polyline_features"]) == 50
    assert "root_cause_classification" in decomposition
    assert "dominant_driver" in decomposition["root_cause_classification"]
    for field in (
        "total_length_m",
        "vertex_count",
        "max_abs_turn_angle_deg",
        "mean_vertex_spacing_m",
    ):
        assert field in decomposition["correlations"]
        assert "pearson" in decomposition["correlations"][field]
        assert "spearman" in decomposition["correlations"][field]
    worst = decomposition["top_50_worst_polyline_features"][0]
    assert {
        "tile_id",
        "source_feature_id",
        "l_inf_m",
        "total_length_m",
        "vertex_count",
        "max_abs_turn_angle_deg",
        "mean_vertex_spacing_m",
    } <= set(worst)


def test_right_angle_decomposition_reports_catastrophic_buckets(
    encoding_primitives,
):
    decomposition = encoding_primitives["right_angle_catastrophic_decomposition_proposed_24_0_5"]
    assert decomposition["candidate"] == {
        "direction_count": 24,
        "magnitude_quantum_m": 0.5,
    }
    bucket_labels = {bucket["bucket"] for bucket in decomposition["buckets"]}
    assert bucket_labels == {
        "<5 deg",
        "5-15 deg",
        "15-45 deg",
        ">45 deg",
    }
    measured = decomposition["measured_right_angle_corner_count"]
    assert measured > 0
    assert sum(bucket["count"] for bucket in decomposition["buckets"]) == measured
    assert "classification" in decomposition
    assert "catastrophic_fraction" in decomposition


def test_linf_chunk_threshold_sweep_reports_all_thresholds(
    encoding_primitives,
):
    sweep = encoding_primitives["l_inf_chunk_threshold_sweep_24_0_5_hierarchical"]
    assert sweep["candidate"] == {
        "direction_count": 24,
        "magnitude_quantum_m": 0.5,
        "anchor_scheme": "hierarchical",
        "geometry_class": "polylines",
    }
    assert [row["chunk_threshold_m"] for row in sweep["rows"]] == [32, 24, 16, 12]
    assert sweep["classification"] == "chunking_is_no_op_on_test_sample"
    assert "proposed_chunk_threshold_m" in sweep
    assert "proposed_l_inf_threshold_m" in sweep
    for row in sweep["rows"]:
        assert row["sample_count"] == 1000
        assert row["skip_count"] == 0
        for field in (
            "roundtrip_l_inf_mean_m",
            "roundtrip_l_inf_p50_m",
            "roundtrip_l_inf_p95_m",
            "roundtrip_l_inf_p99_m",
            "roundtrip_l_inf_max_m",
        ):
            assert field in row
        assert len(row["top_10_worst_polyline_features"]) == 10


def test_proposed_lock_carries_chunk_threshold_metadata(encoding_primitives):
    proposed = encoding_primitives["proposed_lock"]
    sweep = encoding_primitives["l_inf_chunk_threshold_sweep_24_0_5_hierarchical"]
    assert proposed["chunk_threshold_m"] == sweep["proposed_chunk_threshold_m"]
    direction_sweep = encoding_primitives["l_inf_direction_count_sweep_0_5_hierarchical"]
    assert proposed["direction_count"] == direction_sweep["proposed_direction_count"]
    assert proposed["round_trip_l_inf_threshold_status"] == ("LOCKED_HALT_2_APPROVED")


def test_right_angle_root_cause_reports_hypothesis_buckets(encoding_primitives):
    root = encoding_primitives["right_angle_catastrophic_root_cause_24_0_5"]
    assert root["candidate"] == {
        "direction_count": 24,
        "magnitude_quantum_m": 0.5,
    }
    assert root["catastrophic_corner_count"] > 0
    assert {row["bucket"] for row in root["ring_position_buckets"]} == {
        "position_0_or_1",
        "position_2_to_mid",
        "position_mid_to_last",
    }
    assert {row["bucket"] for row in root["input_deviation_buckets"]} == {
        "<1deg",
        "1_to_3deg",
        "3_to_5deg",
    }
    assert {row["bucket"] for row in root["perimeter_buckets"]} == {
        "<10m",
        "10_to_30m",
        "30_to_100m",
        ">100m",
    }
    for bucket_family in (
        "ring_position_buckets",
        "input_deviation_buckets",
        "perimeter_buckets",
    ):
        assert (
            sum(row["count"] for row in root[bucket_family]) == (root["catastrophic_corner_count"])
        )
    assert "root_cause_classification" in root
    assert "classification" in root["root_cause_classification"]


def test_direction_count_sweep_reports_bp2_fit_and_proposal(encoding_primitives):
    sweep = encoding_primitives["l_inf_direction_count_sweep_0_5_hierarchical"]
    assert sweep["candidate"] == {
        "magnitude_quantum_m": 0.5,
        "anchor_scheme": "hierarchical",
        "chunk_threshold_m": 32,
        "geometry_class": "polylines",
    }
    assert [row["direction_count"] for row in sweep["rows"]] == [24, 32, 48, 72]
    assert sweep["proposed_direction_count"] in {24, 48}
    assert "classification" in sweep
    for row in sweep["rows"]:
        assert row["sample_count"] == 1000
        assert row["skip_count"] == 0
        assert row["bp2_fit"]["components"] == {
            "anchor_vocab_size": 96,
            "direction_vocab_size": row["direction_count"],
            "magnitude_vocab_size": 65,
            "structural_sentinel_count": 0,
        }
        assert row["bp2_fit"]["fits_placeholder"] is True
        for field in (
            "roundtrip_l_inf_mean_m",
            "roundtrip_l_inf_p50_m",
            "roundtrip_l_inf_p95_m",
            "roundtrip_l_inf_p99_m",
            "roundtrip_l_inf_max_m",
        ):
            assert field in row


def test_anchor_verification_documents_measurement_inconsistency(
    encoding_primitives,
):
    verification = encoding_primitives["anchor_verification_cross_measurement"]
    assert verification["joint_surface_anchor_scheme"] == "anchor_scheme_independent"
    assert verification["joint_surface_geometry_scope"] == (
        "combined_polylines_and_polygon_exterior_rings"
    )
    assert verification["lock_threshold_surface_anchor_scheme"] == "hierarchical"
    assert verification["verified_inconsistency_cause"] == (
        "geometry_scope_difference_not_anchor_scheme"
    )


def test_right_angle_known_loss_and_threshold_proposal(encoding_primitives):
    proposal = encoding_primitives["right_angle_v1_known_loss_threshold_proposal"]
    root = encoding_primitives["right_angle_catastrophic_root_cause_24_0_5"]
    assert root["right_angle_catastrophic_v1_classification"] == (
        "accepted_v1_known_loss_cascade_8_candidate_for_sub_f_v2"
    )
    assert proposal["threshold_basis"] == "non_catastrophic_post_deviation_p95"
    assert proposal["excluded_catastrophic_gt_45_deg"] is True
    assert proposal["round_trip_angle_threshold_status"] == (
        "PROPOSED_V1_KNOWN_LOSS_EXCLUDING_CATASTROPHIC"
    )
    assert proposal["round_trip_angle_threshold_deg"] > 0


def test_protocol_v2_candidate_9_capture_is_documented(encoding_primitives):
    note = encoding_primitives["protocol_v2_candidate_9_capture"]
    assert note["candidate"] == 9
    assert note["classification"] == "hypothesis_falsified_capture"
    assert "chunk-as-lever hypothesis was falsified" in note["note"]


# ============================================================================
# T8.3 — encoder helpers + canonicalize_geometry (BP5 §5.6 contract)
# ============================================================================


# ---- helpers ---------------------------------------------------------------


def test_quantize_coord_m_integer_only_banker_tiebreak():
    """Per BP5 §5.2 lock: int(round(coord_m / quantum)) Python banker's tie-break."""
    from cfm.data.sub_f.encoder import quantize_coord_m

    # 0.25 / 0.5 = 0.5 -> banker's round-to-even: 0
    assert quantize_coord_m(0.25, quantum_m=0.5) == 0
    # 0.75 / 0.5 = 1.5 -> banker: 2
    assert quantize_coord_m(0.75, quantum_m=0.5) == 2
    # 1.0 / 0.5 = 2.0 -> 2
    assert quantize_coord_m(1.0, quantum_m=0.5) == 2


def test_direction_bin_lower_at_boundary_48_directions():
    """Per BP5 §5.2: tie-break to LOWER bin index. 48 directions = 7.5 deg each.
    3.75 deg is exactly half-bin between dir_0 and dir_1 -> dir_0.
    """
    from cfm.data.sub_f.encoder import direction_bin

    assert direction_bin(0.0, direction_count=48) == 0
    assert direction_bin(3.75, direction_count=48) == 0  # exact half-bin -> lower
    assert direction_bin(7.5, direction_count=48) == 1
    assert direction_bin(359.999, direction_count=48) == 47


# ---- canonicalize_geometry: pre-flight Assertion 2 (routing fidelity) ------


def test_canonicalize_open_linestring_preserves_direction():
    """Per §5.6: LineString direction is PRESERVED (no canonicalization)."""
    from cfm.data.sub_f.encoder import canonicalize_geometry

    forward = LineString([(5, 5), (1, 1)])
    reverse = LineString([(1, 1), (5, 5)])
    assert list(canonicalize_geometry(forward).coords) == [(5, 5), (1, 1)]
    assert list(canonicalize_geometry(reverse).coords) == [(1, 1), (5, 5)]


def test_canonicalize_closed_linestring_preserves_direction():
    """Per §5.6: closed LineString (roundabout) routes to LineString-preserve,
    NOT to ring canonicalization. Anti-pattern this guards: dispatch on
    geom.is_ring (True for closed LineStrings) instead of geom.geom_type.
    """
    from cfm.data.sub_f.encoder import canonicalize_geometry

    roundabout_cw_non_lex_min_start = LineString([(2, 0), (2, 2), (0, 2), (0, 0), (2, 0)])
    expected = [(2, 0), (2, 2), (0, 2), (0, 0), (2, 0)]
    assert list(canonicalize_geometry(roundabout_cw_non_lex_min_start).coords) == expected


def test_canonicalize_polygon_rotates_to_lex_min_start():
    """Per §5.6 rule (i): Polygon ring rotated to start at lex-min vertex."""
    from cfm.data.sub_f.encoder import canonicalize_geometry

    # [(5,5),(1,1),(3,1)] signed area = 8 > 0 -> CCW (RFC 7946 exterior OK)
    poly = Polygon([(5, 5), (1, 1), (3, 1), (5, 5)])
    canon = canonicalize_geometry(poly)
    coords = list(canon.exterior.coords)
    assert coords[0] == (1, 1), f"expected lex-min start (1,1); got {coords[0]}"
    assert coords[0] == coords[-1], "ring must remain closed"


def test_canonicalize_polygon_reverses_cw_winding_to_ccw():
    """Per §5.6 rule (ii): Polygon exterior must be CCW (RFC 7946)."""
    from cfm.data.sub_f.encoder import canonicalize_geometry

    # [(1,1),(5,5),(3,1)] signed area = -8 < 0 -> CW; lex-min (1,1) is first
    poly = Polygon([(1, 1), (5, 5), (3, 1), (1, 1)])
    canon = canonicalize_geometry(poly)
    coords = list(canon.exterior.coords)
    # CCW reverse: (1,1) -> (3,1) -> (5,5) -> (1,1)
    assert coords == [(1, 1), (3, 1), (5, 5), (1, 1)]


def test_canonicalize_multilinestring_sorts_parts_by_first_vertex():
    """Per §5.6 rule (iv): multi-part order = sort by first vertex (= lex-min
    for internally-canonical parts)."""
    from cfm.data.sub_f.encoder import canonicalize_geometry

    part_high = LineString([(3, 3), (7, 7)])
    part_low = LineString([(1, 1), (5, 5)])
    multi_in = MultiLineString([part_high, part_low])
    canon = list(canonicalize_geometry(multi_in).geoms)
    assert next(iter(canon[0].coords)) == (1, 1)
    assert next(iter(canon[1].coords)) == (3, 3)


def test_canonicalize_idempotent_all_geom_types():
    """Per §5.6: canonicalize(canonicalize(g)) == canonicalize(g) for every supported type."""
    from cfm.data.sub_f.encoder import canonicalize_geometry

    inputs = [
        LineString([(5, 5), (1, 1)]),
        Polygon([(5, 5), (1, 1), (3, 1), (5, 5)]),
        MultiLineString([LineString([(3, 3), (7, 7)]), LineString([(1, 1), (5, 5)])]),
        MultiPolygon(
            [
                Polygon([(0, 0), (2, 0), (2, 2), (0, 2), (0, 0)]),
                Polygon([(10, 10), (12, 10), (12, 12), (10, 12), (10, 10)]),
            ]
        ),
    ]
    for g in inputs:
        once = canonicalize_geometry(g)
        twice = canonicalize_geometry(once)
        assert once.wkb == twice.wkb, (
            f"canonicalize not idempotent for {g.geom_type}: once != twice"
        )


# ---- pre-flight Assertion 1: token-count invariance ------------------------


def test_canonicalize_preserves_vertex_count():
    """BP5 <-> BP3 invariance: canonicalization reorders but must not change V.

    The BP3 budget at P99.9 (5,888 padded) was measured on sub-C source-order
    features; T8 emits canonical-order features. The budget remains valid iff
    V(canonical) == V(source) per feature. If canonicalization ever adds /
    removes a closure vertex or normalizes a degenerate ring differently, the
    budget was measured against the wrong number.
    """
    from cfm.data.sub_f.encoder import _vertex_count, canonicalize_geometry

    cases = [
        # (label, source_geom)
        ("polygon_lex_min_rotation", Polygon([(5, 5), (1, 1), (3, 1), (5, 5)])),
        ("polygon_winding_flip", Polygon([(1, 1), (5, 5), (3, 1), (1, 1)])),
        (
            "multilinestring_part_sort",
            MultiLineString([LineString([(3, 3), (7, 7)]), LineString([(1, 1), (5, 5)])]),
        ),
        ("open_linestring_preserve", LineString([(5, 5), (1, 1)])),
        ("closed_linestring_preserve", LineString([(2, 0), (2, 2), (0, 2), (0, 0), (2, 0)])),
    ]
    for label, src in cases:
        canon = canonicalize_geometry(src)
        v_src = _vertex_count(src)
        v_canon = _vertex_count(canon)
        assert v_src == v_canon, f"vertex count drift on {label}: source={v_src} canon={v_canon}"


# ---- encoder 4-case grammar -----------------------------------------------


def _vocab_id(tag: str) -> int:
    """Test helper - looks up token_id by tag from the loaded vocab."""
    from cfm.data.sub_f.vocab import vocab_tag_to_id

    return vocab_tag_to_id()[tag]


def test_encode_feature_case_a_uncrossed_polyline():
    """Case A: uncrossed feature fully within cell.

    Per spec section 3.2 token shape:
      <feature> <semantic_tag>
        <anchor_x_q> <anchor_y_q>             (2 tokens flat; 4 if hierarchical)
        <direction_d> <magnitude_q>           x (V-1) pairs
      <feature_end>

    With BP2 lock (hierarchical anchor, n_anchor=4):
      tokens = 3 + 4 + 2*(V-1) = 7 + 2V

    Test input: 3-vertex polyline; expect token count = 13.
    """
    from cfm.data.sub_f.encoder import encode_feature

    geom = LineString([(10.0, 20.0), (15.0, 25.0), (20.0, 30.0)])
    encoded = encode_feature(geom, semantic_tag="highway=residential")
    assert encoded.case == "A"
    # Per spec §3.2: 1 (<feature>) + 1 (<semantic_tag>) + 4 (hierarchical anchor)
    # + 2*(V-1) dir/mag pairs + 1 (<feature_end>) = 5 + 2V. For V=3: 11 tokens.
    # Plan typo (7 + 2V) fixed in plan + test together; see commit message.
    assert len(encoded.tokens) == 5 + 2 * 3, (
        f"Case A 3-vertex: expected 11 tokens; got {len(encoded.tokens)}"
    )


def test_encode_feature_case_b_outbound_road():
    """Case B: road exiting via one cell edge.

    Per spec section 3.2 token shape:
      <feature> <semantic_tag>
        <anchor_x_q> <anchor_y_q>             (anchor)
        <direction_d> <magnitude_q>           x (V-2) inner pairs
        <bref_dir_class>                       outbound bref (replaces tail
                                                direction+magnitude; net 0
                                                vs Case A's final pair, so
                                                token delta vs A is +1 for
                                                the feature_end shift)

    Pattern: tokens = 1 + 1 + N_anchor + 2*(V-2) + 1 + 1 = 4 + N_anchor + 2*(V-2)
    With n_anchor=4: tokens = 8 + 2*(V-2)
    """
    from cfm.data.sub_f.encoder import encode_feature

    geom = LineString([(10.0, 20.0), (15.0, 25.0), (250.0, 30.0)])
    encoded = encode_feature(
        geom,
        semantic_tag="highway=primary",
        outbound_bref="<bref_E_MAJOR>",
    )
    assert encoded.case == "B"
    V = 3
    assert len(encoded.tokens) == 8 + 2 * (V - 2)
    # Outbound bref must appear once; last token before <feature_end>.
    assert encoded.tokens[-2] == _vocab_id("<bref_E_MAJOR>")


def test_encode_feature_case_c_inbound_road():
    """Case C: road entering from one cell edge.

    Per spec section 3.2 token shape:
      <feature> <semantic_tag>
        <bref_dir_class>                       inbound bref (prepended)
        <anchor_x_q> <anchor_y_q>              entry vertex coords (on edge)
        <direction_d> <magnitude_q>           x (V-1) pairs (chunked per section 3.5)
      <feature_end>

    Base formula (all segments <= 32m, so no chunking):
      tokens = 1 + 1 + 1 + N_anchor + 2*(V-1) + 1 = 8 + 2*(V-1)

    Test uses 25m segments (under the 32m chunk threshold) so the base
    formula holds. A separate test (test_long_segment_chunks_per_spec_3_5)
    covers the chunking path.
    """
    from cfm.data.sub_f.encoder import encode_feature

    geom = LineString([(0.0, 100.0), (25.0, 100.0), (50.0, 100.0)])  # 25m segs
    encoded = encode_feature(
        geom,
        semantic_tag="highway=primary",
        inbound_bref="<bref_W_MAJOR>",
    )
    assert encoded.case == "C"
    V = 3
    assert len(encoded.tokens) == 8 + 2 * (V - 1)
    # Inbound bref is the 3rd token (after <feature>, <semantic_tag>).
    assert encoded.tokens[2] == _vocab_id("<bref_W_MAJOR>")


def test_encode_feature_case_d_through_road():
    """Case D: road inbound AND outbound (through-cell).

    Per spec section 3.2 token shape:
      <feature> <semantic_tag>
        <bref_dir_class>                       inbound
        <anchor_x_q> <anchor_y_q>              entry vertex
        <direction_d> <magnitude_q>           x (V-2) inner pairs (chunked per section 3.5)
        <bref_dir_class>                       outbound
      <feature_end>

    Base formula (all segments <= 32m, so no chunking):
      tokens = 5 + N_anchor + 2*(V-2) = 9 + 2*(V-2)

    Test uses 25m segments under the 32m chunk threshold; chunking covered
    separately by test_long_segment_chunks_per_spec_3_5.
    """
    from cfm.data.sub_f.encoder import encode_feature

    geom = LineString([(0.0, 100.0), (25.0, 100.0), (50.0, 100.0)])  # 25m segs
    encoded = encode_feature(
        geom,
        semantic_tag="highway=primary",
        inbound_bref="<bref_W_MAJOR>",
        outbound_bref="<bref_E_MAJOR>",
    )
    assert encoded.case == "D"
    V = 3
    assert len(encoded.tokens) == 9 + 2 * (V - 2)


def test_long_segment_chunks_per_spec_3_5():
    """Per spec section 3.5: "Magnitudes beyond 32m broken into multiple
    direction + magnitude pairs at the same direction (e.g., a 50m straight
    stretch becomes <direction_0> <magnitude_64> followed by <direction_0>
    <magnitude_36>)."

    Test: a 50m horizontal stretch (anchor + 1 vertex 50m east) must emit
    2 (dir, mag) pairs both pointing east; magnitudes 64 (=32m) + 36 (=18m).
    Total decoded distance = 32m + 18m = 50m.
    """
    from cfm.data.sub_f.encoder import (
        _DIRECTION_BASE,
        _MAGNITUDE_BASE,
        encode_feature,
    )

    geom = LineString([(0.0, 0.0), (50.0, 0.0)])  # 50m east, V=2
    encoded = encode_feature(geom, semantic_tag="highway=residential")
    # Case A; no brefs.
    # Token shape: <feature> <semantic_tag> anchor(4 tokens) (dir,mag)*N <feature_end>
    # 50m / 32m chunk threshold = 2 chunks → 4 tokens for (dir, mag) pairs.
    # Total tokens: 1 + 1 + 4 + 4 + 1 = 11
    assert len(encoded.tokens) == 11, (
        f"expected 11 tokens (1 + 1 + 4 + 4 + 1) for 50m chunked feature; got {len(encoded.tokens)}"
    )
    # Body inspection: skip <feature>, <semantic_tag>, 4 anchor tokens → 4 tokens
    # remaining before <feature_end>. They form 2 (dir, mag) pairs, both
    # pointing east (direction=0 at 7.5° resolution).
    body = encoded.tokens[6:-1]  # 4 tokens
    assert len(body) == 4
    # Both directions are the same (east).
    assert body[0] == body[2]
    # First mag = 64 (max, = 32m); second mag = 36 (= 18m).
    assert body[1] == _MAGNITUDE_BASE + (64 - 1), (
        f"first chunk should be max magnitude (64 quanta = 32m); "
        f"got mag_idx={body[1] - _MAGNITUDE_BASE + 1}"
    )
    assert body[3] == _MAGNITUDE_BASE + (36 - 1), (
        f"second chunk should be remainder (36 quanta = 18m); "
        f"got mag_idx={body[3] - _MAGNITUDE_BASE + 1}"
    )
    # Direction should be east (0° = direction bin 0).
    assert body[0] == _DIRECTION_BASE + 0


def test_chunking_token_count_matches_ceil_distance_over_32():
    """For any segment of length L, the number of emitted (dir, mag) pairs
    equals ceil(L / 32m). The total magnitude across pairs equals L within
    the quantization step (0.5m).

    Tests with L = 32, 64, 96, 100 (boundaries of the chunking behavior).
    """
    import math

    from cfm.data.sub_f.encoder import _direction_magnitude_pair

    for distance_m in (32.0, 32.5, 64.0, 96.0, 100.0):
        tokens = _direction_magnitude_pair(distance_m, 0.0)
        n_pairs = len(tokens) // 2
        assert n_pairs == math.ceil(distance_m / 32.0), (
            f"distance={distance_m}m: expected ceil({distance_m}/32) = "
            f"{math.ceil(distance_m / 32.0)} pairs; got {n_pairs}"
        )


def test_encode_feature_starts_with_feature_marker_ends_with_feature_end():
    """Every encoded feature opens with <feature> and closes with <feature_end>.

    These structural sentinels live at IDs 509 and 510 per the T8 plan-write
    sentinel-inventory fix (consumed from BP2 reserved_v2_headroom front;
    family="structural", distinct from "encoding_primitive"). See spec section
    13.1 "T8 plan-write -> BP2 inventory" row.
    """
    from cfm.data.sub_f.encoder import encode_feature
    from cfm.data.sub_f.vocab import vocab_tag_to_id

    tag_to_id = vocab_tag_to_id()
    expected_feature = tag_to_id["<feature>"]
    expected_feature_end = tag_to_id["<feature_end>"]
    assert expected_feature == 509
    assert expected_feature_end == 510

    geom = LineString([(1.0, 1.0), (2.0, 2.0)])
    encoded = encode_feature(geom, semantic_tag="highway=service")
    assert encoded.tokens[0] == expected_feature
    assert encoded.tokens[-1] == expected_feature_end


def test_encode_feature_uses_bp4_unknown_tag_when_semantic_unmapped():
    """class_raw sentinels (e.g., B__UNK__, unknown) map to BP4 <unknown_*>
    family per spec section 3.3 + cascade #7. encode_feature accepts the raw
    semantic_tag and resolves to BP4 if it's a sub-C sentinel.
    """
    from cfm.data.sub_f.encoder import encode_feature
    from cfm.data.sub_f.vocab import vocab_tag_to_id

    geom = Polygon([(0, 0), (1, 0), (1, 1), (0, 1), (0, 0)])
    # B__UNK__ is a sub-C sentinel; encoder routes to BP4 <unknown_building>.
    encoded = encode_feature(geom, semantic_tag="building=B__UNK__")
    # Expect the BP4 token id for <unknown_building> in the encoded sequence.
    unknown_building_id = vocab_tag_to_id()["<unknown_building>"]
    assert unknown_building_id in encoded.tokens


# ---- per-cell aggregator (§3.3, §4.4) -------------------------------------


def test_encode_cell_empty_emits_empty_token_list():
    """Per spec §4.4: empty cells emit token_sequence = [] (not null)."""
    from cfm.data.sub_f.encoder import EncodedCell, encode_cell

    out = encode_cell(features=[], cell_edges={})
    assert isinstance(out, EncodedCell)
    assert out.tokens == []
    assert out.feature_count == 0


def test_encode_cell_concatenates_per_feature_tokens():
    """Per spec §3.3: cell-level sequence is flat concatenation of per-feature seqs."""
    from shapely.geometry import LineString

    from cfm.data.sub_f.encoder import encode_cell

    features = [
        (LineString([(1.0, 1.0), (2.0, 2.0)]), "highway=service", "A"),
        (LineString([(10.0, 10.0), (20.0, 20.0)]), "highway=residential", "A"),
    ]
    out = encode_cell(
        features=[(geom, tag) for geom, tag, _case in features],
        cell_edges={"N": "NONE", "E": "NONE", "S": "NONE", "W": "NONE"},
    )
    # 2 features x (3 + 4 + 2*1 = 9) tokens each = 18 total
    assert len(out.tokens) == 18
    assert out.feature_count == 2


def test_encode_cell_preserves_sub_c_source_order():
    """Per spec §3.3: features encoded in sub-C row order. Caller controls
    ordering by the order of `features` list. encode_cell does NOT re-sort.
    """
    from shapely.geometry import LineString

    from cfm.data.sub_f.encoder import encode_cell

    f1 = (LineString([(1.0, 1.0), (2.0, 2.0)]), "highway=service")
    f2 = (LineString([(10.0, 10.0), (20.0, 20.0)]), "highway=residential")
    out_12 = encode_cell(
        features=[f1, f2], cell_edges={"N": "NONE", "E": "NONE", "S": "NONE", "W": "NONE"}
    )
    out_21 = encode_cell(
        features=[f2, f1], cell_edges={"N": "NONE", "E": "NONE", "S": "NONE", "W": "NONE"}
    )
    assert out_12.tokens != out_21.tokens, "encode_cell must respect input feature order"


def test_encode_cell_canonicalizes_each_feature():
    """Each feature is passed through canonicalize_geometry before encoding.
    Token output for a non-canonical polygon must equal the output for its
    canonical form.
    """
    from shapely.geometry import Polygon

    from cfm.data.sub_f.encoder import canonicalize_geometry, encode_cell

    raw = Polygon([(5, 5), (1, 1), (3, 1), (5, 5)])  # CCW, non-lex-min start
    canon = canonicalize_geometry(raw)

    out_raw = encode_cell(
        features=[(raw, "building=residential")],
        cell_edges={"N": "NONE", "E": "NONE", "S": "NONE", "W": "NONE"},
    )
    out_canon = encode_cell(
        features=[(canon, "building=residential")],
        cell_edges={"N": "NONE", "E": "NONE", "S": "NONE", "W": "NONE"},
    )
    assert out_raw.tokens == out_canon.tokens, (
        "encode_cell must canonicalize raw inputs internally so output is "
        "invariant to source ordering — required for BP3 token-count invariance"
    )
