"""Tests for sub-F BP2 encoding primitive Halt 2 surface."""

from __future__ import annotations

import math
from pathlib import Path

import pytest
import yaml

CONFIG_ROOT = Path(__file__).resolve().parents[3] / "configs" / "sub_f"
ENCODING_PRIMITIVES_PATH = CONFIG_ROOT / "encoding_primitives.yaml"
SENTINEL_INVENTORY_PATH = CONFIG_ROOT / "sentinel_inventory.yaml"


@pytest.fixture(scope="module")
def encoding_primitives() -> dict:
    assert ENCODING_PRIMITIVES_PATH.exists(), (
        "configs/sub_f/encoding_primitives.yaml must be generated by "
        "scripts/sub_f/analyze_geometry_primitives.py"
    )
    return yaml.safe_load(ENCODING_PRIMITIVES_PATH.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def sentinel_inventory() -> dict:
    return yaml.safe_load(SENTINEL_INVENTORY_PATH.read_text(encoding="utf-8"))


def test_encoding_primitives_status_is_locked(encoding_primitives):
    assert encoding_primitives["_status"] == "LOCKED"


def test_joint_surface_contains_exact_candidate_grid(encoding_primitives):
    rows = encoding_primitives["joint_surface"]
    actual = {
        (row["direction_count"], row["magnitude_quantum_m"])
        for row in rows
    }
    expected = {
        (direction_count, magnitude_quantum_m)
        for direction_count in (8, 16, 24)
        for magnitude_quantum_m in (0.25, 0.5, 1.0)
    }
    assert actual == expected
    assert len(rows) == 9


@pytest.mark.parametrize(
    "field",
    [
        "analytical_angle_half_bin_deg",
        "analytical_magnitude_half_quantum_m",
        "analytical_l_inf_bound_m",
        "roundtrip_l_inf_mean_m",
        "roundtrip_l_inf_p50_m",
        "roundtrip_l_inf_p95_m",
        "roundtrip_l_inf_p99_m",
        "roundtrip_l_inf_max_m",
        "roundtrip_sample_counts",
        "roundtrip_skip_counts",
    ],
)
def test_joint_surface_rows_include_analytical_and_linf_fields(
    encoding_primitives, field
):
    for row in encoding_primitives["joint_surface"]:
        assert field in row


@pytest.mark.parametrize(
    "field",
    [
        "right_angle_post_roundtrip_mean_deg",
        "right_angle_post_roundtrip_p50_deg",
        "right_angle_post_roundtrip_p95_deg",
        "right_angle_post_roundtrip_p99_deg",
        "right_angle_post_roundtrip_max_deg",
        "right_angle_abs_change_mean_deg",
        "right_angle_abs_change_p50_deg",
        "right_angle_abs_change_p95_deg",
        "right_angle_abs_change_p99_deg",
        "right_angle_abs_change_max_deg",
        "right_angle_measured_corner_count",
        "right_angle_skip_count",
    ],
)
def test_joint_surface_rows_include_right_angle_fields(encoding_primitives, field):
    for row in encoding_primitives["joint_surface"]:
        assert field in row


def test_input_characterization_reports_all_tile_inventory(encoding_primitives):
    source_scope = encoding_primitives["source_scope"]
    characterization = encoding_primitives["input_geometry_characterization"]
    assert source_scope["tile_count"] > 1
    assert source_scope["feature_count"] > 0
    assert characterization["geometry_type_feature_counts"]
    assert sum(characterization["geometry_type_feature_counts"].values()) == (
        source_scope["feature_count"]
    )
    assert characterization["measured_geometry_sample_counts"]["polylines"] > 0
    assert characterization["measured_geometry_sample_counts"]["polygon_exterior_rings"] > 0


def test_right_angle_input_characterization_reports_fraction(encoding_primitives):
    right_angle = encoding_primitives["right_angle_input_characterization"]
    assert right_angle["total_building_polygon_corner_count"] > 0
    assert "fraction_within_5_deg_of_90" in right_angle
    assert 0.0 <= right_angle["fraction_within_5_deg_of_90"] <= 1.0
    assert right_angle["definition"] == "abs(angle_deg - 90) <= 5"


def test_collinearity_derivation_reports_distribution_and_method(
    encoding_primitives,
):
    collinearity = encoding_primitives["collinearity_candidate_distribution"]
    assert collinearity["total_polyline_interior_triples"] > 0
    assert "collinear_candidate_triples" in collinearity
    assert "weak_empirical_p95_basis" in collinearity
    assert collinearity["weak_empirical_p95_basis"] == (
        collinearity["collinear_candidate_triples"] < 500
    )
    assert collinearity["distribution_perpendicular_m"]["count"] == (
        collinearity["collinear_candidate_triples"]
    )
    assert "proposed_threshold_method" in collinearity
    assert "proposed_threshold_m" in collinearity
    assert "fixed_multiple_thresholds_m" in collinearity
    assert {"1x_magnitude_quantum", "2x_magnitude_quantum"} <= set(
        collinearity["fixed_multiple_thresholds_m"]
    )


def test_anchor_comparison_includes_flat_and_hierarchical(encoding_primitives):
    comparison = encoding_primitives["anchor_scheme_comparison"]
    assert {row["scheme"] for row in comparison} == {"flat", "hierarchical"}
    for row in comparison:
        assert row["anchor_vocab_size"] > 0
        assert row["tokens_per_anchor"] > 0
        assert row["mean_sequence_length_per_cell"] > 0
        assert row["p95_sequence_length_per_cell"] > 0


def test_anchor_vocab_derivation_is_spec_locked(encoding_primitives):
    quantum = encoding_primitives["proposed_lock"]["magnitude_quantum_m"]
    comparison = {
        row["scheme"]: row
        for row in encoding_primitives["anchor_scheme_comparison"]
    }
    assert comparison["flat"]["anchor_vocab_size"] == 2 * math.ceil(250 / quantum)
    assert comparison["flat"]["vocab_derivation"] == (
        "2 * ceil(250 / magnitude_quantum_m)"
    )
    assert comparison["hierarchical"]["anchor_vocab_size"] == 96
    assert comparison["hierarchical"]["vocab_derivation"] == (
        "(16 coarse + 32 fine) * 2 axes"
    )


def test_proposed_lock_uses_approved_halt2_values(
    encoding_primitives,
):
    proposed = encoding_primitives["proposed_lock"]
    assert proposed["direction_count"] == 48
    assert proposed["magnitude_quantum_m"] == 0.5
    assert proposed["anchor_scheme"] == "hierarchical"
    assert proposed["chunk_threshold_m"] == 32
    assert proposed["round_trip_l_inf_threshold_m"] == 4.8
    assert proposed["round_trip_l_inf_threshold_status"] == (
        "LOCKED_HALT_2_APPROVED"
    )
    assert proposed["round_trip_angle_threshold_deg"] == 7.5
    assert proposed["round_trip_angle_threshold_status"] == (
        "LOCKED_HALT_2_APPROVED"
    )
    assert proposed["collinearity_admission_perpendicular_m"] == 0.928048


def test_bp2_placeholder_fit_references_reserved_block(encoding_primitives):
    fit = encoding_primitives["bp2_placeholder_fit"]
    assert fit["placeholder_start_id"] == 300
    assert fit["placeholder_end_id"] == 1499
    assert fit["placeholder_range"] == "300..1499"
    assert fit["fits_placeholder"] is True
    assert fit["components"]["anchor_vocab_size"] == 96
    assert fit["components"]["direction_vocab_size"] == (
        encoding_primitives["proposed_lock"]["direction_count"]
    )
    assert fit["components"]["magnitude_vocab_size"] == 65


def test_encoding_primitives_lock_metadata_preserves_methodology(
    encoding_primitives,
):
    lock = encoding_primitives["lock_metadata"]
    assert lock["halt"] == "Halt 2"
    assert lock["status"] == "APPROVED_LOCKED"
    assert lock["measurement_methodology"]["deterministic_seed"] == 20260523
    assert lock["measurement_methodology"]["l_inf_scope"] == "polyline_only"
    assert lock["measurement_methodology"]["angle_threshold_scope"] == (
        "non_catastrophic_right_angle_corners_only"
    )
    assert lock["measurement_methodology"]["catastrophic_angle_exclusion"] == (
        "post_roundtrip_abs_deviation_from_90_deg > 45"
    )
    assert lock["cascade_8_candidate"]["candidate"] == (
        "BP2 anchor + direction-bin alignment"
    )
    assert "cascade #8" in lock["cascade_8_candidate"]["note"]
    assert lock["chunking_classification"]["classification"] == (
        "chunking_is_no_op_on_test_sample"
    )
    assert lock["chunking_classification"]["reference"] == (
        "Continuation #2 Item A"
    )
    assert lock["source_config_cross_references"] == [
        "configs/sub_f/semantic_vocab.yaml",
        "configs/sub_f/unknown_family.yaml",
        "configs/sub_f/sentinel_inventory.yaml",
    ]


def test_sentinel_inventory_locks_bp2_subranges(sentinel_inventory):
    bp2 = sentinel_inventory["bp2_encoding_primitives"]
    assert bp2["start_id"] == 300
    assert bp2["end_id"] == 1499
    assert bp2["status"] == "LOCKED at Halt 2 approval"
    assert bp2["placeholder"] is False
    assert bp2["used_count"] == 209
    assert bp2["reserved_count"] == 991
    assert bp2["sub_blocks"] == {
        "anchor": {"start_id": 300, "end_id": 395, "slot_count": 96},
        "direction": {"start_id": 396, "end_id": 443, "slot_count": 48},
        "magnitude": {"start_id": 444, "end_id": 508, "slot_count": 65},
        "reserved_v2_headroom": {
            "start_id": 509,
            "end_id": 1499,
            "slot_count": 991,
        },
    }
    assert "bp2_encoding_primitives_placeholder" not in sentinel_inventory


def test_sentinel_inventory_keeps_bp7_placeholder(sentinel_inventory):
    bp7 = sentinel_inventory["bp7_boundary_ref_placeholder"]
    assert bp7["start_id"] == 1500
    assert bp7["end_id"] == 1599
    assert bp7["placeholder"] is True


def test_linf_decomposition_reports_top_50_and_driver_summary(
    encoding_primitives,
):
    decomposition = encoding_primitives["l_inf_decomposition_proposed_24_0_5"]
    assert decomposition["candidate"] == {
        "direction_count": 24,
        "magnitude_quantum_m": 0.5,
        "geometry_class": "polylines",
    }
    assert decomposition["sample_count"] == 1000
    assert len(decomposition["top_50_worst_polyline_features"]) == 50
    assert "root_cause_classification" in decomposition
    assert "dominant_driver" in decomposition["root_cause_classification"]
    for field in (
        "total_length_m",
        "vertex_count",
        "max_abs_turn_angle_deg",
        "mean_vertex_spacing_m",
    ):
        assert field in decomposition["correlations"]
        assert "pearson" in decomposition["correlations"][field]
        assert "spearman" in decomposition["correlations"][field]
    worst = decomposition["top_50_worst_polyline_features"][0]
    assert {
        "tile_id",
        "source_feature_id",
        "l_inf_m",
        "total_length_m",
        "vertex_count",
        "max_abs_turn_angle_deg",
        "mean_vertex_spacing_m",
    } <= set(worst)


def test_right_angle_decomposition_reports_catastrophic_buckets(
    encoding_primitives,
):
    decomposition = encoding_primitives[
        "right_angle_catastrophic_decomposition_proposed_24_0_5"
    ]
    assert decomposition["candidate"] == {
        "direction_count": 24,
        "magnitude_quantum_m": 0.5,
    }
    bucket_labels = {bucket["bucket"] for bucket in decomposition["buckets"]}
    assert bucket_labels == {
        "<5 deg",
        "5-15 deg",
        "15-45 deg",
        ">45 deg",
    }
    measured = decomposition["measured_right_angle_corner_count"]
    assert measured > 0
    assert sum(bucket["count"] for bucket in decomposition["buckets"]) == measured
    assert "classification" in decomposition
    assert "catastrophic_fraction" in decomposition


def test_linf_chunk_threshold_sweep_reports_all_thresholds(
    encoding_primitives,
):
    sweep = encoding_primitives["l_inf_chunk_threshold_sweep_24_0_5_hierarchical"]
    assert sweep["candidate"] == {
        "direction_count": 24,
        "magnitude_quantum_m": 0.5,
        "anchor_scheme": "hierarchical",
        "geometry_class": "polylines",
    }
    assert [row["chunk_threshold_m"] for row in sweep["rows"]] == [32, 24, 16, 12]
    assert sweep["classification"] == "chunking_is_no_op_on_test_sample"
    assert "proposed_chunk_threshold_m" in sweep
    assert "proposed_l_inf_threshold_m" in sweep
    for row in sweep["rows"]:
        assert row["sample_count"] == 1000
        assert row["skip_count"] == 0
        for field in (
            "roundtrip_l_inf_mean_m",
            "roundtrip_l_inf_p50_m",
            "roundtrip_l_inf_p95_m",
            "roundtrip_l_inf_p99_m",
            "roundtrip_l_inf_max_m",
        ):
            assert field in row
        assert len(row["top_10_worst_polyline_features"]) == 10


def test_proposed_lock_carries_chunk_threshold_metadata(encoding_primitives):
    proposed = encoding_primitives["proposed_lock"]
    sweep = encoding_primitives["l_inf_chunk_threshold_sweep_24_0_5_hierarchical"]
    assert proposed["chunk_threshold_m"] == sweep["proposed_chunk_threshold_m"]
    direction_sweep = encoding_primitives["l_inf_direction_count_sweep_0_5_hierarchical"]
    assert proposed["direction_count"] == direction_sweep["proposed_direction_count"]
    assert proposed["round_trip_l_inf_threshold_status"] == (
        "LOCKED_HALT_2_APPROVED"
    )


def test_right_angle_root_cause_reports_hypothesis_buckets(encoding_primitives):
    root = encoding_primitives["right_angle_catastrophic_root_cause_24_0_5"]
    assert root["candidate"] == {
        "direction_count": 24,
        "magnitude_quantum_m": 0.5,
    }
    assert root["catastrophic_corner_count"] > 0
    assert {row["bucket"] for row in root["ring_position_buckets"]} == {
        "position_0_or_1",
        "position_2_to_mid",
        "position_mid_to_last",
    }
    assert {row["bucket"] for row in root["input_deviation_buckets"]} == {
        "<1deg",
        "1_to_3deg",
        "3_to_5deg",
    }
    assert {row["bucket"] for row in root["perimeter_buckets"]} == {
        "<10m",
        "10_to_30m",
        "30_to_100m",
        ">100m",
    }
    for bucket_family in (
        "ring_position_buckets",
        "input_deviation_buckets",
        "perimeter_buckets",
    ):
        assert sum(row["count"] for row in root[bucket_family]) == (
            root["catastrophic_corner_count"]
        )
    assert "root_cause_classification" in root
    assert "classification" in root["root_cause_classification"]


def test_direction_count_sweep_reports_bp2_fit_and_proposal(encoding_primitives):
    sweep = encoding_primitives["l_inf_direction_count_sweep_0_5_hierarchical"]
    assert sweep["candidate"] == {
        "magnitude_quantum_m": 0.5,
        "anchor_scheme": "hierarchical",
        "chunk_threshold_m": 32,
        "geometry_class": "polylines",
    }
    assert [row["direction_count"] for row in sweep["rows"]] == [24, 32, 48, 72]
    assert sweep["proposed_direction_count"] in {24, 48}
    assert "classification" in sweep
    for row in sweep["rows"]:
        assert row["sample_count"] == 1000
        assert row["skip_count"] == 0
        assert row["bp2_fit"]["components"] == {
            "anchor_vocab_size": 96,
            "direction_vocab_size": row["direction_count"],
            "magnitude_vocab_size": 65,
            "structural_sentinel_count": 0,
        }
        assert row["bp2_fit"]["fits_placeholder"] is True
        for field in (
            "roundtrip_l_inf_mean_m",
            "roundtrip_l_inf_p50_m",
            "roundtrip_l_inf_p95_m",
            "roundtrip_l_inf_p99_m",
            "roundtrip_l_inf_max_m",
        ):
            assert field in row


def test_anchor_verification_documents_measurement_inconsistency(
    encoding_primitives,
):
    verification = encoding_primitives["anchor_verification_cross_measurement"]
    assert verification["joint_surface_anchor_scheme"] == "anchor_scheme_independent"
    assert verification["joint_surface_geometry_scope"] == (
        "combined_polylines_and_polygon_exterior_rings"
    )
    assert verification["lock_threshold_surface_anchor_scheme"] == "hierarchical"
    assert verification["verified_inconsistency_cause"] == (
        "geometry_scope_difference_not_anchor_scheme"
    )


def test_right_angle_known_loss_and_threshold_proposal(encoding_primitives):
    proposal = encoding_primitives["right_angle_v1_known_loss_threshold_proposal"]
    root = encoding_primitives["right_angle_catastrophic_root_cause_24_0_5"]
    assert root["right_angle_catastrophic_v1_classification"] == (
        "accepted_v1_known_loss_cascade_8_candidate_for_sub_f_v2"
    )
    assert proposal["threshold_basis"] == "non_catastrophic_post_deviation_p95"
    assert proposal["excluded_catastrophic_gt_45_deg"] is True
    assert proposal["round_trip_angle_threshold_status"] == (
        "PROPOSED_V1_KNOWN_LOSS_EXCLUDING_CATASTROPHIC"
    )
    assert proposal["round_trip_angle_threshold_deg"] > 0


def test_protocol_v2_candidate_9_capture_is_documented(encoding_primitives):
    note = encoding_primitives["protocol_v2_candidate_9_capture"]
    assert note["candidate"] == 9
    assert note["classification"] == "hypothesis_falsified_capture"
    assert "chunk-as-lever hypothesis was falsified" in note["note"]
