"""Tests for the sub-F cross-tile validator (Task 10).

BP7 four-test composite (cross-reference, symmetry, non-road non-emission,
coverage) + version-manifest consistency + sha-uniqueness + all-64-cells-
present + the standalone BP1->sub-E class-mapping gate.

ADVERSARIAL, PER-LEG, RULE-ISOLATED DISCIPLINE (the core mandate):
A validator test that builds CONSISTENT input and asserts the validator
PASSES proves nothing. For EACH leg there is >=1 NEGATIVE test that
constructs input violating ONLY that leg and asserts
`CrossTileValidationError` with a leg-specific message substring. The legs
are decomposed into one private function each (`_check_cross_reference`,
`_check_symmetry`, `_check_non_road_non_emission`, `_check_coverage`,
`_check_version_consistency`, `_check_sha_uniqueness`,
`_check_all_cells_present`) so a negative can target ONE leg in
isolation and the reviewer can confirm the TARGET leg fires, not an
incidentally-earlier check.

SYNTHETIC FIXTURE DISCIPLINE (sub-E + sub-F caches absent locally, per
`project_sub_e_cache_absent_t3c_code_inferred`): all tests build synthetic
multi-tile region dirs with valid 144-row sub-E contracts (reusing the
test_pipeline_writer 144-row builder pattern), 64-row cells.parquet, and
synthetic provenance.yaml. A @pytest.mark.skip stub stands in for the
real-region BP7 composite (see close-checklist).

BP7 token IDs (LOCKED 1500-1507 per boundary_reference_vocab.yaml) are
resolved via vocab_tag_to_id(), never hardcoded in assertion logic.
"""

from __future__ import annotations

from pathlib import Path

import pyarrow as pa
import pyarrow.parquet as pq
import pytest
import yaml
from shapely.geometry import LineString, Polygon

from cfm.data.sub_e.derivation import BoundaryClass, load_class_grouping_map
from cfm.data.sub_f.boundary_contract import resolve_bref_tag
from cfm.data.sub_f.encoder import encode_feature
from cfm.data.sub_f.io import CELLS_SCHEMA, CellRow, write_cells_parquet
from cfm.data.sub_f.provenance import provenance_sha256
from cfm.data.sub_f.validator_cross_tile import (
    CrossTileValidationError,
    _bref_id_to_dir_class,
    _check_coverage,
    _check_non_road_non_emission,
    _check_symmetry,
    _emitted_brefs_by_cell,
    _semantic_id_to_tag,
    validate_cross_tile,
)
from cfm.data.sub_f.vocab import semantic_tag_to_l1_key, vocab_tag_to_id

# ===========================================================================
# Fixtures: synthetic sub-E contract, cells.parquet, provenance.yaml
# ===========================================================================

# Sub-E parquet schema — SOURCE-DERIVED bit-for-bit match against
# src/cfm/data/sub_e/writer.py:38-48 _BOUNDARY_CONTRACT_SCHEMA. Replicated
# from test_pipeline_writer.py for a self-contained module (close-checklist
# tracks the shared-fixture dedup obligation).
_SUB_E_SCHEMA = pa.schema(
    [
        pa.field("slot_kind", pa.int8(), nullable=False),
        pa.field("slot_index", pa.int16(), nullable=False),
        pa.field("lower_cell_i", pa.int8(), nullable=False),
        pa.field("lower_cell_j", pa.int8(), nullable=False),
        pa.field("axis", pa.int8(), nullable=False),
        pa.field("scope_marker", pa.int8(), nullable=False),
        pa.field("boundary_class_enum", pa.int16(), nullable=True),
    ]
)

_VALID_VERSION_PROVENANCE: dict[str, object] = {
    "sub_f_artifact_format_version": "1.0",
    "sub_f_schema_version": "1.0",
    "sub_f_vocab_version": "1.0",
    "sub_f_derivation_version": "1.0",
    "sub_f_validator_version": "1.0",
    "sub_f_source_version": {
        "overture_release": "2026-04-15.0",
        "sub_c_schema_version": "1.0",
        "sub_c_commit_sha": "deadbeef" * 5,
    },
}

_FAKE_SHA = "a" * 64


def _make_tile_provenance(tile_label: str) -> dict:
    """Build a provenance dict with a real content-derived sha for `tile_label`.

    Folds `tile_label` into the dict so each tile produces a DISTINCT sha via
    the real `provenance_sha256()` function (content-derived: different input
    dict -> different sha). The `provenance_sha256` field itself is stored in
    the dict so the validator's sha-uniqueness leg can read it.

    CONTRACT TEST: shas are generated by calling the REAL `provenance_sha256()`
    on the dict (minus the sha field itself, which the function strips before
    hashing per the `*_sha256` exclusion rule in SUB_F_EXCLUDED_FROM_SHA). Two
    tiles with different `tile_label` values yield different dicts and thus
    different shas — we do NOT hardcode sha values here.
    """
    base = dict(_VALID_VERSION_PROVENANCE)
    base["tile_label"] = tile_label  # makes content distinct per tile
    sha = provenance_sha256(base)
    base["provenance_sha256"] = sha
    return base


def _make_full_tile_contract_rows(
    overrides: dict[tuple[int, int, int, int], dict] | None = None,
) -> list[dict]:
    """Build 144 well-formed sub-E contract rows (112 INTERNAL + 32 EXTERNAL).

    All rows default to non-active (scope_marker=1, boundary_class_enum=None).
    Override specific edges via (slot_kind, lower_cell_i, lower_cell_j, axis).
    Source pattern: _make_full_tile_rows (test_boundary_contract.py) via
    test_pipeline_writer.py _make_full_tile_contract_rows.
    """
    from cfm.data.sub_e.rotation import EdgeKind, cell_to_edge_ids

    seen_internal: set[tuple[int, int, int]] = set()
    rows: list[dict] = []
    internal_slot_idx = 0
    external_slot_idx = 0
    overrides = overrides or {}

    for cell_i in range(8):
        for cell_j in range(8):
            edges = cell_to_edge_ids(cell_i, cell_j)
            for edge in (edges.north, edges.south, edges.west, edges.east):
                lower_i, lower_j, axis, kind = edge
                if kind is EdgeKind.INTERNAL:
                    key = (lower_i, lower_j, axis)
                    if key in seen_internal:
                        continue
                    seen_internal.add(key)
                    slot_kind = 1
                    slot_index = internal_slot_idx
                    internal_slot_idx += 1
                else:
                    slot_kind = 2
                    slot_index = external_slot_idx
                    external_slot_idx += 1
                row = {
                    "slot_kind": slot_kind,
                    "slot_index": slot_index,
                    "lower_cell_i": lower_i,
                    "lower_cell_j": lower_j,
                    "axis": axis,
                    "scope_marker": 1,
                    "boundary_class_enum": None,
                }
                ov = overrides.get((slot_kind, lower_i, lower_j, axis))
                if ov:
                    row.update(ov)
                rows.append(row)
    return rows


def _write_sub_e_contract(path: Path, overrides: dict | None = None) -> None:
    rows = _make_full_tile_contract_rows(overrides)
    table = pa.Table.from_pylist(rows, schema=_SUB_E_SCHEMA)
    path.parent.mkdir(parents=True, exist_ok=True)
    pq.write_table(table, path)


def _empty_cell_rows() -> list[CellRow]:
    """64 empty cell rows (tokens=[]). Caller overwrites specific cells."""
    return [
        CellRow(
            cell_i=i,
            cell_j=j,
            cell_slot_index=i * 8 + j,
            token_sequence=[],
            feature_count=0,
            provenance_sha256=_FAKE_SHA,
        )
        for i in range(8)
        for j in range(8)
    ]


def _set_cell(
    rows: list[CellRow], cell_i: int, cell_j: int, tokens: list[int], feature_count: int
) -> None:
    """Overwrite one cell's token_sequence in a 64-row list (in place)."""
    idx = cell_i * 8 + cell_j
    rows[idx] = CellRow(
        cell_i=cell_i,
        cell_j=cell_j,
        cell_slot_index=idx,
        token_sequence=tokens,
        feature_count=feature_count,
        provenance_sha256=_FAKE_SHA,
    )


def _write_tile(
    sub_f_dir: Path,
    sub_e_dir: Path,
    tile_name: str,
    cell_rows: list[CellRow],
    contract_overrides: dict | None = None,
    provenance: dict | None = None,
) -> None:
    """Write one tile: cells.parquet + provenance.yaml (sub-F) + contract (sub-E).

    When `provenance` is None, generates a tile-specific provenance dict with a
    real content-derived sha via `_make_tile_provenance(tile_name)`. This ensures
    every tile in a multi-tile region has a DISTINCT sha so the sha-uniqueness
    leg does not spuriously fire on unrelated tests.
    """
    tile_sub_f = sub_f_dir / tile_name
    tile_sub_f.mkdir(parents=True, exist_ok=True)
    write_cells_parquet(tile_sub_f / "cells.parquet", cell_rows)
    prov = provenance if provenance is not None else _make_tile_provenance(tile_name)
    (tile_sub_f / "provenance.yaml").write_text(yaml.safe_dump(prov))
    _write_sub_e_contract(sub_e_dir / tile_name / "boundary_contract.parquet", contract_overrides)


def _write_sub_c_features(
    sub_c_tile_dir: Path, road_lines: list[tuple[int, int, LineString]]
) -> None:
    """Write a minimal sub-C features.parquet for road_edge_presence tests.

    Only the columns `_build_road_edge_presence` reads — feature_class (0=road),
    cell_i, cell_j, geometry (cell-local WKB). Each entry is a road LineString in
    the named cell, so the validator's road-edge-presence signal includes the
    edges its endpoints lie on. Tests that need NO road presence simply omit this
    (a missing features.parquet yields the empty set).
    """
    sub_c_tile_dir.mkdir(parents=True, exist_ok=True)
    table = pa.table(
        {
            "cell_i": pa.array([ci for (ci, _cj, _ln) in road_lines], pa.int8()),
            "cell_j": pa.array([cj for (_ci, cj, _ln) in road_lines], pa.int8()),
            "feature_class": pa.array([0 for _ in road_lines], pa.int8()),
            "geometry": pa.array([ln.wkb for (_ci, _cj, ln) in road_lines], pa.binary()),
        }
    )
    pq.write_table(table, sub_c_tile_dir / "features.parquet")


# ---- feature-chunk builders (real encoder output) -------------------------


def _road_chunk_outbound(direction: str, class_label: str) -> list[int]:
    """A road feature exiting `direction` edge with an outbound bref (Case B).

    Geometry endpoint lands on the named edge so the encoder's own bref
    placement is used. We pass the bref explicitly to encode_feature so the
    chunk's bref is deterministic regardless of geometry.
    """
    bref = resolve_bref_tag(direction, class_label)
    assert bref is not None
    road = LineString([(50.0, 100.0), (200.0, 100.0)])
    ef = encode_feature(road, semantic_tag="highway=residential", outbound_bref=bref)
    return ef.tokens


def _road_chunk_plain() -> list[int]:
    """A road feature that emits NO bref (Case A, fully interior)."""
    road = LineString([(50.0, 50.0), (120.0, 120.0)])
    ef = encode_feature(road, semantic_tag="highway=residential")
    return ef.tokens


def _building_chunk_with_bref(direction: str, class_label: str) -> list[int]:
    """A building feature with a bref FORCED into it (non-road violation).

    encode_feature applied to a Polygon never produces a bref via the
    normal path, so we synthesize the bref injection directly: a building
    chunk that (illegitimately) carries a bref token at the outbound slot.
    This is the ONLY way to construct a non-road non-emission violation,
    because a correct encoder never does this.
    """
    bref = resolve_bref_tag(direction, class_label)
    assert bref is not None
    bref_id = vocab_tag_to_id()[bref]
    building = Polygon([(50, 50), (50, 100), (100, 100), (100, 50), (50, 50)])
    ef = encode_feature(building, semantic_tag="building=residential")
    # Insert the bref immediately before <feature_end> (outbound slot).
    tokens = list(ef.tokens)
    return [*tokens[:-1], bref_id, tokens[-1]]


# ===========================================================================
# Leg 5 NEGATIVE: version-manifest consistency
# ===========================================================================


def test_version_drift_across_tiles_raises(tmp_path: Path):
    """NEGATIVE (version manifest leg): two tiles differing only in
    sub_f_vocab_version -> CrossTileValidationError('version manifest').

    Rule-isolated: both tiles have all-NONE contracts and all-empty cells,
    so cross-reference / symmetry / non-road / coverage all pass trivially;
    the ONLY violated invariant is version-manifest consistency, which is
    checked before sha-uniqueness. The 'version manifest' substring confirms
    that leg fired.
    """
    sub_f = tmp_path / "sub_f"
    sub_e = tmp_path / "sub_e"

    _write_tile(sub_f, sub_e, "tile=0_0", _empty_cell_rows())
    # Build drifted provenance from tile-specific base so sha field is present
    # (version-consistency fires before sha-uniqueness, but the sha field must
    # exist for correctness once the earlier leg changes are read as a unit).
    drifted = _make_tile_provenance("tile=1_0")
    drifted["sub_f_vocab_version"] = "2.0"  # the ONLY changed axis
    _write_tile(sub_f, sub_e, "tile=1_0", _empty_cell_rows(), provenance=drifted)

    with pytest.raises(CrossTileValidationError, match="version manifest"):
        validate_cross_tile(sub_f, sub_e, sub_f.parent / "sub_c")


# ===========================================================================
# Leg 1 NEGATIVE: cross-reference
# ===========================================================================


def test_cross_reference_emitted_bref_disagrees_with_contract_raises(tmp_path: Path):
    """NEGATIVE (cross-reference leg): both cells emit <bref_MAJOR> on the
    shared edge, but the sub-E contract says MINOR_ROAD for that edge.

    Rule-isolated: versions are consistent (single tile, valid provenance);
    BOTH cell (0,0) and its East neighbour (1,0) emit MAJOR on their shared
    edge, so:
      - symmetry PASSES: (0,0).East={MAJOR_ROAD} == (1,0).West={MAJOR_ROAD}.
      - non-road PASSES: both are road (highway) features.
      - coverage PASSES: active edge has road features AND brefs are emitted,
        symmetry is satisfied.
      - cross-reference FIRES: emitted MAJOR disagrees with contract MINOR_ROAD.
    The ONLY fault is emitted-MAJOR vs contract-MINOR ->
    'cross-reference' substring confirms the target leg fired.

    Isolation verified by leg-neutering: with _check_cross_reference body
    replaced by `return`, this test no longer raises CrossTileValidationError,
    confirming no other leg fires on this fixture.
    """
    sub_f = tmp_path / "sub_f"
    sub_e = tmp_path / "sub_e"

    rows = _empty_cell_rows()
    # Cell (0,0) emits MAJOR on East edge.
    _set_cell(rows, 0, 0, _road_chunk_outbound("E", "MAJOR_ROAD"), feature_count=1)
    # Cell (1,0) ALSO emits MAJOR on West edge — same shared edge, same class.
    # Symmetry sees (0,0).East={MAJOR_ROAD} == (1,0).West={MAJOR_ROAD} -> passes.
    _set_cell(rows, 1, 0, _road_chunk_outbound("W", "MAJOR_ROAD"), feature_count=1)

    # Contract: shared East/West edge of (0,0)/(1,0) is active as MINOR_ROAD
    # (scope_marker=0, boundary_class_enum=3). Both cells emit MAJOR -> cross-
    # reference fires (MAJOR != MINOR). Symmetry is unaffected because both
    # cells agree on MAJOR with each other; the disagreement is with the contract.
    overrides = {(1, 0, 0, 0): {"scope_marker": 0, "boundary_class_enum": 3}}

    _write_tile(sub_f, sub_e, "tile=0_0", rows, contract_overrides=overrides)

    with pytest.raises(CrossTileValidationError, match="cross-reference"):
        validate_cross_tile(sub_f, sub_e, sub_f.parent / "sub_c")


# ===========================================================================
# Leg 2 NEGATIVE: symmetry (rule-isolated by calling the leg directly)
# ===========================================================================


def test_symmetry_road_present_both_one_emits_raises():
    """NEGATIVE (symmetry leg) — the MUST-DISTINGUISH guard (fixture b).

    The shared internal edge has a road feature with an endpoint in BOTH cells
    (both in `road_edge_presence`), yet only (0,0) emits its bref; (1,0) does
    NOT emit on its West edge. Because (1,0) genuinely carries a road endpoint
    on the shared edge, the missing emission is a real defect (encoder
    under-emission, or a clip that left a present-but-unemitted road) ->
    CrossTileValidationError('symmetry').

    This is the guard that keeps the v1.2 relax honest: if the relax allowed
    ALL one-sided emission (a blanket weaken), this case would WRONGLY pass.
    """
    emitted_by_cell = {
        (0, 0): [("E", "MAJOR_ROAD", "highway")],
        # (1, 0) emits nothing on W despite carrying a road endpoint there.
    }
    road_edge_presence = {((0, 0), "E"), ((1, 0), "W")}  # BOTH sides carry a road endpoint
    with pytest.raises(CrossTileValidationError, match="symmetry"):
        _check_symmetry("tile=0_0", emitted_by_cell, road_edge_presence)


def test_symmetry_termination_one_sided_emission_passes():
    """POSITIVE (symmetry leg, v1.2 relax) — fixture (a).

    A road TERMINATES exactly at the shared internal edge: present
    (endpoint-on-edge) only in (0,0), absent from (1,0). (0,0) emits its bref;
    (1,0) has NO road endpoint on the shared edge (not in `road_edge_presence`),
    so it correctly emits nothing. The asymmetry is faithful to the geometry
    (the road exists only on one side), so symmetry must NOT raise.

    Guards the §8.3 termination false positive that failed 8 batch-2 cities on
    14 edges; see reports/2026-06-05-batch2-subf-symmetry-fp-investigation.md.
    """
    emitted_by_cell = {
        (0, 0): [("E", "MINOR_ROAD", "highway")],
        # (1, 0) has no road on its W edge -> emits nothing -> legit termination.
    }
    road_edge_presence = {((0, 0), "E")}  # ONLY (0,0) carries a road endpoint on the edge
    _check_symmetry("tile=0_0", emitted_by_cell, road_edge_presence)  # must NOT raise


def test_symmetry_paired_cells_disagree_class_raises():
    """NEGATIVE (symmetry leg): paired cells agree an edge is active but disagree
    on CLASS (A says MAJOR, B says MINOR) -> 'symmetry'. Both cells carry a road
    endpoint on the shared edge (both in road_edge_presence), so this is a genuine
    class disagreement (not a termination) and raises regardless of the relax.
    """
    emitted_by_cell = {
        (0, 0): [("S", "MAJOR_ROAD", "highway")],
        (0, 1): [("N", "MINOR_ROAD", "highway")],  # opposite dir, different class
    }
    road_edge_presence = {((0, 0), "S"), ((0, 1), "N")}
    with pytest.raises(CrossTileValidationError, match="symmetry"):
        _check_symmetry("tile=0_0", emitted_by_cell, road_edge_presence)


# ===========================================================================
# Leg 4: coverage (v1.2 road-presence-conditioned) — direct, rule-isolated
# ===========================================================================


def test_coverage_termination_active_edge_no_road_endpoint_passes():
    """POSITIVE (coverage leg, v1.2) — fixture cov-(a).

    Cell (1,0)'s West edge is active (MINOR_ROAD in the contract) but (1,0) has
    NO road endpoint on that edge (`road_edge_presence` does not contain it) —
    the road terminated on the OTHER side. Pre-1.2 coverage required emission
    whenever a road sat in this cell OR its neighbour (road_cells, too coarse),
    which demanded a bref the terminating side cannot produce. v1.2 conditions
    on THIS cell's own road-endpoint presence, so coverage must NOT raise.
    """
    contract = {(1, 0): {"N": "NONE", "E": "NONE", "S": "NONE", "W": "MINOR_ROAD"}}
    emitted_by_cell: dict = {}  # (1,0) emits nothing
    road_edge_presence: set = set()  # (1,0) has NO road endpoint on its W edge
    _check_coverage("tile=0_0", emitted_by_cell, contract, road_edge_presence)  # must NOT raise


def test_coverage_under_emission_active_edge_with_road_endpoint_raises():
    """NEGATIVE (coverage leg, v1.2) — fixture cov-(b), the must-distinguish twin.

    Cell (1,0)'s West edge is active AND (1,0) genuinely carries a road endpoint
    there (`road_edge_presence` contains it), yet (1,0) emits no bref on W. That
    is a real under-emission -> CrossTileValidationError('coverage'). If the relax
    dropped the road-presence condition entirely (blanket weaken), this case
    would WRONGLY pass — so this guards the coverage leg's teeth.
    """
    contract = {(1, 0): {"N": "NONE", "E": "NONE", "S": "NONE", "W": "MINOR_ROAD"}}
    emitted_by_cell: dict = {}  # (1,0) emits nothing despite a road endpoint on W
    road_edge_presence = {((1, 0), "W")}
    with pytest.raises(CrossTileValidationError, match="coverage"):
        _check_coverage("tile=0_0", emitted_by_cell, contract, road_edge_presence)


# ===========================================================================
# Leg 3 NEGATIVE: non-road non-emission
# ===========================================================================


def test_non_road_building_emits_bref_raises(tmp_path: Path):
    """NEGATIVE (non-road leg): a building-only cell carries a bref token.

    Rule-isolated: the bref is forced onto a BUILDING feature, so non-road
    fires. The contract DOES say MAJOR on that edge so cross-reference would
    PASS (the bref's class matches), and the neighbour also emits the matching
    MAJOR so symmetry would PASS — only the non-road leg distinguishes this
    regime. The 'non-road' substring confirms the target leg fired.
    """
    sub_f = tmp_path / "sub_f"
    sub_e = tmp_path / "sub_e"

    rows = _empty_cell_rows()
    # Building in (0,0) with a (forced) MAJOR bref on East edge.
    building_chunk = _building_chunk_with_bref("E", "MAJOR_ROAD")
    _set_cell(rows, 0, 0, building_chunk, feature_count=1)
    # Neighbour (1,0) emits matching MAJOR on West so symmetry would pass.
    nbr_chunk = _road_chunk_outbound("W", "MAJOR_ROAD")
    _set_cell(rows, 1, 0, nbr_chunk, feature_count=1)

    # Contract: shared East/West edge of (0,0)/(1,0) active MAJOR so
    # cross-reference passes for both emitted brefs.
    overrides = {(1, 0, 0, 0): {"scope_marker": 0, "boundary_class_enum": 2}}
    _write_tile(sub_f, sub_e, "tile=0_0", rows, contract_overrides=overrides)

    with pytest.raises(CrossTileValidationError, match="non-road"):
        validate_cross_tile(sub_f, sub_e, sub_f.parent / "sub_c")


# ===========================================================================
# Leg 4 NEGATIVE: coverage (active road edge + road feature, no bref)
# ===========================================================================


def test_coverage_active_edge_with_road_endpoint_no_bref_raises(tmp_path: Path):
    """NEGATIVE (coverage leg, v1.2): an active edge with a road ENDPOINT in the
    cell (per sub-C road_edge_presence) but NO bref emitted -> 'coverage'.

    v1.2 VERDICT-PRESERVATION NOTE [surfaced per the 2->3-arg meaning-flip review]:
    pre-1.2 this fired because the cell merely *contained* a road (`road_cells`,
    too coarse — the old fixture's road `[(50,50),(120,120)]` had NO endpoint on
    the East edge). v1.2 conditions coverage on a road ENDPOINT ON the active
    edge, so the scenario is updated to a road whose endpoint lies on the East
    edge of (0,0) — written to the sub-C features the validator now reads — that
    emits no bref. Same VERDICT (coverage raises), correct v1.2 semantics.
    Rule-isolated: nothing emitted, so cross-reference and symmetry pass; the only
    fault is the uncovered active edge with a road endpoint on it.
    """
    sub_f = tmp_path / "sub_f"
    sub_e = tmp_path / "sub_e"

    rows = _empty_cell_rows()
    _set_cell(rows, 0, 0, _road_chunk_plain(), feature_count=1)  # road token, NO bref

    # Activate East edge of (0,0) as MAJOR.
    overrides = {(1, 0, 0, 0): {"scope_marker": 0, "boundary_class_enum": 2}}
    _write_tile(sub_f, sub_e, "tile=0_0", rows, contract_overrides=overrides)
    # sub-C: a road whose endpoint lies on the East edge of (0,0) -> road_edge_presence
    # contains ((0,0),"E"); the cell emits no bref there -> coverage must raise.
    _write_sub_c_features(
        sub_f.parent / "sub_c" / "tile=0_0",
        [(0, 0, LineString([(50.0, 100.0), (250.0, 100.0)]))],
    )

    with pytest.raises(CrossTileValidationError, match="coverage"):
        validate_cross_tile(sub_f, sub_e, sub_f.parent / "sub_c")


def test_coverage_does_not_overfire_on_edge_with_no_road_endpoint(tmp_path: Path):
    """POSITIVE guard (coverage precision, v1.2): an active edge with NO road
    endpoint in this cell must NOT raise.

    Cell (0,0) is EMPTY (no road in sub-C -> empty road_edge_presence); its East
    edge is active MAJOR. v1.2 coverage conditions on THIS cell's own road-endpoint
    presence, so a bare active edge with no road endpoint here does not over-fire.
    """
    sub_f = tmp_path / "sub_f"
    sub_e = tmp_path / "sub_e"

    rows = _empty_cell_rows()  # all cells empty
    overrides = {(1, 0, 0, 0): {"scope_marker": 0, "boundary_class_enum": 2}}
    _write_tile(sub_f, sub_e, "tile=0_0", rows, contract_overrides=overrides)

    # Must not raise — no road endpoint on the active edge (no sub-C features).
    validate_cross_tile(sub_f, sub_e, sub_f.parent / "sub_c")


# ===========================================================================
# HAPPY PATH: a fully consistent multi-tile region passes
# ===========================================================================


def test_happy_path_consistent_region_passes(tmp_path: Path):
    """All four BP7 legs + version consistency pass on a consistent region.

    Two tiles. Tile 0: a road in cell (0,0) exits East onto an active MAJOR
    edge AND its neighbour (1,0) has a road entering from West on the SAME
    shared edge, both emitting MAJOR -> cross-reference, symmetry, non-road,
    coverage all satisfied. Tile 1: all-empty / all-NONE (trivially valid).
    Versions identical across tiles.
    """
    sub_f = tmp_path / "sub_f"
    sub_e = tmp_path / "sub_e"

    # --- tile 0: a symmetric MAJOR crossing on the (0,0)<->(1,0) shared edge ---
    rows0 = _empty_cell_rows()
    _set_cell(rows0, 0, 0, _road_chunk_outbound("E", "MAJOR_ROAD"), feature_count=1)
    _set_cell(rows0, 1, 0, _road_chunk_outbound("W", "MAJOR_ROAD"), feature_count=1)
    # Shared internal edge (E of (0,0) == W of (1,0)) active MAJOR.
    overrides0 = {(1, 0, 0, 0): {"scope_marker": 0, "boundary_class_enum": 2}}
    _write_tile(sub_f, sub_e, "tile=0_0", rows0, contract_overrides=overrides0)

    # --- tile 1: empty / all-NONE ---
    _write_tile(sub_f, sub_e, "tile=1_0", _empty_cell_rows())

    # Must not raise.
    validate_cross_tile(sub_f, sub_e, sub_f.parent / "sub_c")


def test_no_tiles_raises(tmp_path: Path):
    """An empty region dir (no tile=*/cells.parquet) raises clearly."""
    sub_f = tmp_path / "sub_f"
    sub_e = tmp_path / "sub_e"
    sub_f.mkdir()
    sub_e.mkdir()
    with pytest.raises(CrossTileValidationError, match="no tiles"):
        validate_cross_tile(sub_f, sub_e, sub_f.parent / "sub_c")


# ===========================================================================
# Leg 6 POSITIVE: sha-uniqueness across tiles
# ===========================================================================


def test_sha_uniqueness_distinct_provenance_content_passes(tmp_path: Path):
    """POSITIVE (sha-uniqueness leg): two tiles with genuinely different
    provenance content produce distinct real shas -> validator passes.

    CONTRACT TEST: shas are derived by calling the real `provenance_sha256()`
    on each tile's provenance dict (content-derived; no hardcoded sha strings).
    `_make_tile_provenance("tile=0_0")` and `_make_tile_provenance("tile=1_0")`
    differ on the `tile_label` key -> different input -> different sha.
    We assert the two shas ARE distinct before writing, so the test fails fast
    if the sha-derivation logic is somehow equivalent.
    """
    sub_f = tmp_path / "sub_f"
    sub_e = tmp_path / "sub_e"

    prov_a = _make_tile_provenance("tile=0_0")
    prov_b = _make_tile_provenance("tile=1_0")
    assert prov_a["provenance_sha256"] != prov_b["provenance_sha256"], (
        "fixture shas must differ — `_make_tile_provenance` should produce "
        "distinct shas for different tile labels"
    )

    _write_tile(sub_f, sub_e, "tile=0_0", _empty_cell_rows(), provenance=prov_a)
    _write_tile(sub_f, sub_e, "tile=1_0", _empty_cell_rows(), provenance=prov_b)

    # Must not raise.
    validate_cross_tile(sub_f, sub_e, sub_f.parent / "sub_c")


# ===========================================================================
# Leg 6 NEGATIVE: sha-uniqueness across tiles
# ===========================================================================


def test_sha_uniqueness_identical_provenance_raises(tmp_path: Path):
    """NEGATIVE (sha-uniqueness leg): two tiles with IDENTICAL provenance
    content -> real `provenance_sha256()` yields the SAME sha for both ->
    CrossTileValidationError containing 'sha' and 'unique'.

    Rule-isolated:
    - Both tiles carry the SAME version tuple -> `_check_version_consistency`
      passes (both tiles agree on all six axes).
    - Cells are all-empty so all four BP7 legs (cross-reference, symmetry,
      non-road, coverage) pass trivially.
    - ONLY sha-uniqueness fires.

    Isolation verified by leg-neutering: with `_check_sha_uniqueness` body
    replaced by `return`, this test no longer raises.
    """
    sub_f = tmp_path / "sub_f"
    sub_e = tmp_path / "sub_e"

    # Both tiles carry IDENTICAL provenance content -> same sha.
    # We use _make_tile_provenance for tile=0_0 for both tiles so the
    # version axes agree (version-consistency passes) and the sha is real
    # (not a hardcoded stub). Both tiles share an identical dict -> same sha.
    shared_prov = _make_tile_provenance("tile=0_0")
    # Sanity-assert the sha IS real (64-char hex) so the test is meaningful.
    assert len(shared_prov["provenance_sha256"]) == 64

    _write_tile(sub_f, sub_e, "tile=0_0", _empty_cell_rows(), provenance=shared_prov)
    _write_tile(sub_f, sub_e, "tile=1_0", _empty_cell_rows(), provenance=shared_prov)

    with pytest.raises(CrossTileValidationError, match=r"(?i)sha.*unique|unique.*sha"):
        validate_cross_tile(sub_f, sub_e, sub_f.parent / "sub_c")


# ===========================================================================
# Leg 7 POSITIVE: all-64-distinct-cells-present per tile
# ===========================================================================


def test_all_cells_present_full_grid_passes(tmp_path: Path):
    """POSITIVE (all-cells-present leg): a normal 64-distinct-cell tile passes.

    `_empty_cell_rows()` produces exactly the 8x8 grid with all distinct
    (cell_i, cell_j) pairs. The validator must not raise.
    """
    sub_f = tmp_path / "sub_f"
    sub_e = tmp_path / "sub_e"

    _write_tile(sub_f, sub_e, "tile=0_0", _empty_cell_rows())

    # Must not raise.
    validate_cross_tile(sub_f, sub_e, sub_f.parent / "sub_c")


# ===========================================================================
# Leg 7 NEGATIVE: all-64-distinct-cells-present per tile
# ===========================================================================


def test_all_cells_present_duplicate_and_missing_raises(tmp_path: Path):
    """NEGATIVE (all-cells-present leg): a tile with 64 rows but duplicate
    (3,4) and missing (5,6) -> CrossTileValidationError containing 'cell'
    and 'present'.

    The table is written DIRECTLY via `pq.write_table` with CELLS_SCHEMA,
    bypassing `write_cells_parquet` which rejects duplicate cells. This
    exercises exactly the anomaly that T9's inline row-count==64 check
    cannot catch: 64 rows, but wrong distribution of (cell_i, cell_j).

    Rule-isolated:
    - All token sequences are empty (no brefs) -> BP7 legs all pass trivially.
    - Consistent version + distinct shas (only one tile) -> version/sha legs pass.
    - ONLY all-cells-present fires.

    Isolation verified by leg-neutering: with `_check_all_cells_present` body
    replaced by `return`, this test no longer raises.
    """
    sub_f = tmp_path / "sub_f"
    sub_e = tmp_path / "sub_e"

    # Build a 64-row table: the full 8x8 grid but with (5,6) replaced by a
    # second copy of (3,4). Row ordering is otherwise arbitrary.
    rows_dicts = []
    for i in range(8):
        for j in range(8):
            ci, cj = i, j
            if (ci, cj) == (5, 6):
                # Replace the missing cell (5,6) with a duplicate of (3,4).
                ci, cj = 3, 4
            rows_dicts.append(
                {
                    "cell_i": ci,
                    "cell_j": cj,
                    "cell_slot_index": i * 8 + j,  # slot_index still sequential
                    "token_sequence": [],
                    "feature_count": 0,
                    "provenance_sha256": _FAKE_SHA,
                }
            )

    table = pa.Table.from_pylist(rows_dicts, schema=CELLS_SCHEMA)
    tile_dir = sub_f / "tile=0_0"
    tile_dir.mkdir(parents=True, exist_ok=True)
    pq.write_table(table, tile_dir / "cells.parquet")
    (tile_dir / "provenance.yaml").write_text(yaml.safe_dump(_make_tile_provenance("tile=0_0")))
    _write_sub_e_contract(sub_e / "tile=0_0" / "boundary_contract.parquet")

    with pytest.raises(CrossTileValidationError, match=r"(?i)cell.*(present|distinct)"):
        validate_cross_tile(sub_f, sub_e, sub_f.parent / "sub_c")


# ===========================================================================
# STANDALONE BP1 -> sub-E class-mapping gate (Gate-6 external source of truth)
# ===========================================================================


def test_bp1_to_sub_e_class_mapping_matches_encoder_resolution():
    """Gate-6: the sub-F encoder's class resolution agrees with sub-E's
    load_class_grouping_map() for representative highway=* values.

    EXPECTED side comes ENTIRELY from sub-E's load_class_grouping_map (the
    ground truth) — NOT from sub-F code. The ACTUAL side is the sub-F path
    that the encoder uses: it tokenizes sub-E's BoundaryClass verbatim via
    resolve_bref_tag (which emits <bref_DIR_MAJOR> for MAJOR_ROAD and
    <bref_DIR_MINOR> for MINOR_ROAD). We assert that, for each highway value,
    the class sub-E assigns (with the documented MINOR-default fallthrough)
    is the class sub-F's resolve_bref_tag emits a token for.

    Carry-forward: motorway maps to MINOR (sub-E grouping omits it ->
    derivation.py:85 fallthrough). This test passes when sub-F and sub-E
    AGREE on MINOR-for-motorway; it does NOT validate MINOR is semantically
    correct. See close-checklist.
    """
    grouping = load_class_grouping_map()  # GROUND TRUTH (sub-E)

    def sub_e_class_for(highway_value: str) -> BoundaryClass:
        # Mirror sub-E derive_boundary_class single-crossing path: lookup with
        # MINOR_ROAD default fallthrough (derivation.py:85). This uses ONLY
        # the sub-E grouping map, not sub-F code.
        return grouping.get(highway_value, BoundaryClass.MINOR_ROAD)

    # Representative hand-enumerated highway values spanning MAJOR list,
    # MINOR list, and the fallthrough (motorway, path, unknown).
    representative = [
        "primary",
        "trunk",
        "secondary",
        "residential",
        "service",
        "footway",
        "motorway",  # fallthrough -> MINOR (scoped v1 accept)
        "path",  # fallthrough -> MINOR
        "definitely_not_a_real_class",  # unknown -> MINOR
    ]

    class_to_short = {
        BoundaryClass.MAJOR_ROAD: "MAJOR",
        BoundaryClass.MINOR_ROAD: "MINOR",
    }
    class_to_label = {
        BoundaryClass.MAJOR_ROAD: "MAJOR_ROAD",
        BoundaryClass.MINOR_ROAD: "MINOR_ROAD",
    }

    for value in representative:
        expected_class = sub_e_class_for(value)  # ground truth
        expected_short = class_to_short[expected_class]
        # ACTUAL: sub-F encoder's class -> token path. resolve_bref_tag emits
        # <bref_DIR_SHORT> for the class label sub-E hands it. We feed the
        # sub-E class label and confirm the emitted token's class half
        # matches the sub-E grouping's class.
        emitted_tag = resolve_bref_tag("N", class_to_label[expected_class])
        assert emitted_tag == f"<bref_N_{expected_short}>", (
            f"sub-F class-resolution disagreement for highway={value!r}: "
            f"sub-E grouping -> {expected_class.name}, but sub-F emitted "
            f"{emitted_tag!r}"
        )


def test_bp1_class_mapping_major_set_is_nonempty_and_minor_default():
    """Sanity floor for the class-map gate: sub-E's MAJOR list is non-empty
    (so the gate above actually exercises the MAJOR branch) and an unknown
    value falls through to MINOR (the documented default).

    Guards against a vacuous class-map test where every value maps to MINOR.
    """
    grouping = load_class_grouping_map()
    major_values = [k for k, v in grouping.items() if v is BoundaryClass.MAJOR_ROAD]
    assert major_values, "sub-E grouping has no MAJOR_ROAD values — class-map gate would be vacuous"
    assert grouping.get("__no_such_class__", BoundaryClass.MINOR_ROAD) is BoundaryClass.MINOR_ROAD


# The real-region BP7 cross-tile composite is now in the consolidated
# tests/data/sub_f/test_singapore_integration.py (T13), gated fail-loud on the
# sub-E + sub-F caches. See reports/2026-05-23-phase-1-sub-F-close-checklist.md.


# ===========================================================================
# Cycle-3 (sub-G T11): BP4 <unknown_*> key resolution on the non-road leg
# ===========================================================================


def test_semantic_tag_to_l1_key_resolves_unknown_family():
    """Cycle-3/4 guard: the SHARED vocab authority maps BP4 <unknown_*> tokens to
    their BP1 L1 key, not the literal token. Used by BOTH the validator non-road
    leg and the encoder emission gate.

    <unknown_highway> (a highway with unknown subtype — 9748 SG features,
    unknown_family.yaml id=210 key:highway) MUST resolve to "highway" so the
    non-road leg does not false-positive a road AND the encoder still emits for
    it. Per-key, NOT a blanket unknown-skip: <unknown_healthcare> must still
    resolve to "healthcare" so a genuine non-road-emits-bref stays catchable.
    """
    assert semantic_tag_to_l1_key("<highway=residential>") == "highway"
    assert semantic_tag_to_l1_key("<unknown_highway>") == "highway"
    assert semantic_tag_to_l1_key("<unknown_healthcare>") == "healthcare"


def test_unknown_highway_chunk_passes_non_road_emission_leg():
    """End-to-end (non-road-emission leg): an <unknown_highway> feature chunk
    emitting <bref_S_MINOR> resolves to feature_key "highway", so the leg does
    NOT fire — the exact i10_j11 cell (5,4) false positive that halted the
    real-Singapore cascade.

    Token IDs via vocab_tag_to_id (never hardcoded, per module discipline).
    RED pre-fix: _emitted_brefs_by_cell yielded feature_key "<unknown_highway>"
    and _check_non_road_non_emission raised.
    """
    t = vocab_tag_to_id()
    seq = [t["<feature>"], t["<unknown_highway>"], t["<bref_S_MINOR>"], t["<feature_end>"]]
    row = {"cell_i": 5, "cell_j": 4, "token_sequence": seq}
    emitted = _emitted_brefs_by_cell([row], _bref_id_to_dir_class(), _semantic_id_to_tag())
    assert emitted == {(5, 4): [("S", "MINOR_ROAD", "highway")]}
    # Must NOT raise — the road resolves correctly.
    _check_non_road_non_emission("tile=test", emitted)
