cities:
- a_coruna
- almere
- amsterdam
- barcelona
- berlin
- bologna
- bruges
- budapest
- cergy
- copenhagen
- debrecen
- edinburgh
- eindhoven
- eisenhuttenstadt
- espoo
- glasgow
- hamburg
- helsinki
- karlsruhe
- krakow
- linz
- lisbon
- ljubljana
- lodz
- lyon
- madrid
- malmo
- manchester
- mannheim
- milton_keynes
- munich
- paris
- prague
- rome
- rotterdam
- singapore
- szczecin
- tallinn
- telford
- tilburg
- toledo
- turin
- tychy
- umea
- valencia
- vienna
- warsaw
- welwyn
- wolfsburg
registry_schema_version: '1.0'
registry_sha256: 34186f7091745b6be5fbda593df3f7bfc26a89a340abe4ca6657648a3c7123ac
